//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "author")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub author_id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manga_artist::Entity")]
    MangaArtist,
    #[sea_orm(has_many = "super::manga_author::Entity")]
    MangaAuthor,
}

impl Related<super::manga_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MangaArtist.def()
    }
}

impl Related<super::manga_author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MangaAuthor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
