//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "genre")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub genre_id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manga_genre::Entity")]
    MangaGenre,
}

impl Related<super::manga_genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MangaGenre.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
