//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "manga_listing")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub manga_listing_id: i32,
    pub manga_id: String,
    pub cover_url: String,
    pub name: String,
    pub genres: String,
    pub description_small: String,
    pub public_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
