//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub mod prelude;

pub mod account;
pub mod author;
pub mod chapter;
pub mod chapter_page;
pub mod genre;
pub mod linkage_correction;
pub mod manga;
pub mod manga_artist;
pub mod manga_author;
pub mod manga_genre;
pub mod manga_listing;
pub mod problem_child;
pub mod source;
pub mod source_pattern;
pub mod title;
