//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::account::Entity as Account;
pub use super::author::Entity as Author;
pub use super::chapter::Entity as Chapter;
pub use super::chapter_page::Entity as ChapterPage;
pub use super::genre::Entity as Genre;
pub use super::linkage_correction::Entity as LinkageCorrection;
pub use super::manga::Entity as Manga;
pub use super::manga_artist::Entity as MangaArtist;
pub use super::manga_author::Entity as MangaAuthor;
pub use super::manga_genre::Entity as MangaGenre;
pub use super::manga_listing::Entity as MangaListing;
pub use super::problem_child::Entity as ProblemChild;
pub use super::source::Entity as Source;
pub use super::source_pattern::Entity as SourcePattern;
pub use super::title::Entity as Title;
