//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: String,
    pub name: String,
    pub priority: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manga::Entity")]
    Manga,
    #[sea_orm(has_many = "super::source_pattern::Entity")]
    SourcePattern,
}

impl Related<super::manga::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manga.def()
    }
}

impl Related<super::source_pattern::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourcePattern.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
